// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAFTSC1ZkU8HAX7vUYsTow6VKFFy-ncV4',
    appId: '1:929999561129:web:9261c2fca06671954124b8',
    messagingSenderId: '929999561129',
    projectId: 'foodo-42393',
    authDomain: 'foodo-42393.firebaseapp.com',
    storageBucket: 'foodo-42393.firebasestorage.app',
    measurementId: 'G-04L3980QSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPq-VjWq-U0ueH41nxKkgPrC4-8Xbb3cM',
    appId: '1:929999561129:android:318a57a7836d3a614124b8',
    messagingSenderId: '929999561129',
    projectId: 'foodo-42393',
    storageBucket: 'foodo-42393.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGDZGCH1a72Kz3YwvRcURUBDTmKZYj-Tk',
    appId: '1:929999561129:ios:98cd15779b4019034124b8',
    messagingSenderId: '929999561129',
    projectId: 'foodo-42393',
    storageBucket: 'foodo-42393.firebasestorage.app',
    iosBundleId: 'com.example.foodSpot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGDZGCH1a72Kz3YwvRcURUBDTmKZYj-Tk',
    appId: '1:929999561129:ios:98cd15779b4019034124b8',
    messagingSenderId: '929999561129',
    projectId: 'foodo-42393',
    storageBucket: 'foodo-42393.firebasestorage.app',
    iosBundleId: 'com.example.foodSpot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAFTSC1ZkU8HAX7vUYsTow6VKFFy-ncV4',
    appId: '1:929999561129:web:e036870fae2ab4904124b8',
    messagingSenderId: '929999561129',
    projectId: 'foodo-42393',
    authDomain: 'foodo-42393.firebaseapp.com',
    storageBucket: 'foodo-42393.firebasestorage.app',
    measurementId: 'G-LR8F24PHC7',
  );
}
